version: 2
updates:
- package-ecosystem: maven
  directory: "/java"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/net/JonGallant.Azure.Identity.Extensions.Tests"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/net/JonGallant.Azure.Identity.Extensions"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
